name = "foyer-photos"
main = "src/index.ts"
compatibility_date = "2026-08-22"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "foyer-photos"
database_id = "5870dc0a-48ff-45af-b786-ce2599a1f61e"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "foyer-photos"

[images]
binding = "IMAGES"
