export const textes = {
  titreSite: "Photos du foyer",
  entreeTitre: "Entrer",
  identifiant: "Identifiant",
  motDePasse: "Mot de passe",
  boutonEntrer: "Entrer",
  champsVides: "Veuillez remplir l’identifiant et le mot de passe.",
  identifiantsIncorrects: "Identifiant ou mot de passe incorrect.",
  sortie: "Se déconnecter",
  galerie: "Galerie",
  corbeille: "Corbeille",
  ajouter: "Ajouter des photos",
  aucunePhoto: "Aucune photo pour l’instant.",
  aucunePhotoAide: "Ajoutez des photos du foyer : elles resteront privées.",
  corbeilleVide: "La corbeille est vide.",
  corbeilleVideAide: "Les photos mises à la corbeille apparaîtront ici jusqu’au vidage.",
  datePriseInconnue: "Date de prise de vue inconnue",
  dateAjout: "Ajoutée le",
  datePrise: "Prise de vue",
  dimensions: "Dimensions",
  poids: "Poids",
  nomFichier: "Nom",
  telecharger: "Télécharger",
  mettreCorbeille: "Mettre à la corbeille",
  confirmerCorbeille: "Mettre cette photo à la corbeille ? Vous pourrez la restaurer ensuite.",
  restaurer: "Restaurer",
  viderCorbeille: "Vider la corbeille",
  confirmerVidage:
    "Vider la corbeille ? Les photos seront détruites définitivement et la place sera libérée.",
  retourGalerie: "Retour à la galerie",
  photoIntrouvable: "Cette photo n’est pas disponible.",
  photoEnCorbeille: "Cette photo est à la corbeille. Restaurez-la pour la télécharger.",
  formatRefuse: "Ce fichier n’est pas une photo acceptée.",
  tropLourd: "La photo dépasse la taille acceptée (50 Mo).",
  plusDePlace: "Il n’y a plus assez de place (9 Go).",
  stockageIndisponible: "L’enregistrement a échoué. Réessayez.",
  affichageImpossible: "Cette photo n’a pas pu être préparée pour l’affichage.",
  formatsAcceptes: "JPEG, PNG, WebP, GIF, HEIC ou AVIF — 50 Mo maximum par photo. Plusieurs centaines d’un coup, c’est possible.",
  fichiersIgnores: "fichiers ignorés (pas des photos).",
  quotaCorbeille: "dont à la corbeille — videz la corbeille pour libérer de la place.",
  toutRestaurer: "Tout restaurer",
  confirmerToutRestaurer: "Restaurer toutes les photos de la corbeille ?",
  espaceUtilise: "Espace utilisé",
  envoiEnCours: "Envoi en cours…",
  envoiInterrompu: "Envoi interrompu : la photo n’a pas été enregistrée.",
  choisirFichiers: "Choisir des photos",
  selectionner: "Sélectionner",
  toutSelectionner: "Tout sélectionner",
  toutDeselectionner: "Tout désélectionner",
  annulerSelection: "Annuler",
  unePhotoSelectionnee: "1 photo sélectionnée",
  photosSelectionnees: "photos sélectionnées",
  confirmerCorbeillePlusieurs:
    "Mettre ces photos à la corbeille ? Vous pourrez les restaurer ensuite.",
  telechargerEnCours: "Téléchargement en cours…",
  rangement: "Rangement",
  plusRecentes: "Plus récentes d’abord",
  plusAnciennes: "Plus anciennes d’abord",
} as const
